services:
  backend:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.8-alpine3.18
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'task_manager_db'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - habrdb-data:/var/lib/postgresql/data

volumes:
  habrdb-data: